-- ============================================================================
-- COMPLETE SUPABASE DATABASE SCHEMA
-- Translation Web Service - All Tables and Features
-- ============================================================================
-- Run this entire script in your Supabase SQL Editor
-- This creates all tables needed for:
--   - User authentication (hardcoded users)
--   - Translation logging
--   - Comments and highlighting
--   - Feedback and ratings (including thumbs up/down)
-- ============================================================================

-- ============================================================================
-- 1. USERS TABLE (Hardcoded Login Users)
-- ============================================================================
-- Stores user information for authentication
-- Users are defined in auth.py but can also be stored here for reference

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT,  -- Optional: for future password hashing
  user_id TEXT NOT NULL UNIQUE,  -- Internal user ID (e.g., "user_001")
  full_name TEXT,
  email TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default users (matching auth.py)
-- Note: In production, passwords should be hashed
INSERT INTO users (username, user_id, full_name, is_active) 
VALUES 
  ('admin', 'user_001', 'Administrator', true),
  ('user', 'user_002', 'Standard User', true)
ON CONFLICT (username) DO NOTHING;

-- Create indexes for users
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_user_id ON users(user_id);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active) WHERE is_active = true;

-- Enable RLS for users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Allow public read on users" ON users;

-- Create policy (allow reading user info)
CREATE POLICY "Allow public read on users" ON users
  FOR SELECT
  USING (true);

-- ============================================================================
-- 2. TRANSLATION LOGS TABLE
-- ============================================================================
-- Stores every translation generated by all engines

CREATE TABLE IF NOT EXISTS translation_logs (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  translation_model TEXT NOT NULL,
  source_text TEXT NOT NULL,
  translated_text TEXT NOT NULL,
  translation_id TEXT,
  file_name TEXT,
  file_type TEXT,
  language_pair TEXT DEFAULT 'English-Telugu',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_translation_logs_user_id ON translation_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_translation_logs_model ON translation_logs(translation_model);
CREATE INDEX IF NOT EXISTS idx_translation_logs_translation_id ON translation_logs(translation_id);
CREATE INDEX IF NOT EXISTS idx_translation_logs_created_at ON translation_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_translation_logs_file_type ON translation_logs(file_type) WHERE file_type IS NOT NULL;

-- Enable Row Level Security (RLS)
ALTER TABLE translation_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public insert on translation_logs" ON translation_logs;
DROP POLICY IF EXISTS "Allow public read on translation_logs" ON translation_logs;

-- Create policies
CREATE POLICY "Allow public insert on translation_logs" ON translation_logs
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow public read on translation_logs" ON translation_logs
  FOR SELECT
  USING (true);

-- ============================================================================
-- 3. COMMENTS TABLE
-- ============================================================================
-- Stores highlighted text selections and comments on documents

CREATE TABLE IF NOT EXISTS comments (
  id BIGSERIAL PRIMARY KEY,
  translation_id TEXT NOT NULL,
  doc_type TEXT NOT NULL CHECK (doc_type IN ('original', 'translated')),
  engine TEXT,  -- Which translation engine (if translated)
  selected_text TEXT NOT NULL,
  comment TEXT NOT NULL,
  text_position INTEGER,  -- Optional: position in document (deprecated, kept for compatibility)
  thumbs_rating TEXT CHECK (thumbs_rating IS NULL OR thumbs_rating IN ('up', 'down')),  -- Thumbs up/down rating
  user_id TEXT,  -- User who made the comment
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_comments_translation_id ON comments(translation_id);
CREATE INDEX IF NOT EXISTS idx_comments_doc_type ON comments(doc_type);
CREATE INDEX IF NOT EXISTS idx_comments_engine ON comments(engine) WHERE engine IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_thumbs_rating ON comments(thumbs_rating) WHERE thumbs_rating IS NOT NULL;

-- Enable Row Level Security (RLS)
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public insert on comments" ON comments;
DROP POLICY IF EXISTS "Allow public read on comments" ON comments;
DROP POLICY IF EXISTS "Allow public delete on comments" ON comments;

-- Create policies
CREATE POLICY "Allow public insert on comments" ON comments
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow public read on comments" ON comments
  FOR SELECT
  USING (true);

CREATE POLICY "Allow public delete on comments" ON comments
  FOR DELETE
  USING (true);

-- ============================================================================
-- 4. FEEDBACK TABLE
-- ============================================================================
-- Stores user ratings, feedback, and thumbs up/down votes

CREATE TABLE IF NOT EXISTS feedback (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT,  -- User who submitted feedback
  translation_id TEXT,  -- Translation session ID
  translation_model TEXT,  -- Which engine was rated (indictrans2, gemini-3-pro, etc.)
  file_type TEXT,  -- Type of document
  language_pair TEXT DEFAULT 'English-Telugu',
  translation_method TEXT,  -- Same as translation_model (for compatibility)
  
  -- Rating fields (0-10 scale, nullable for partial submissions)
  overall_quality INTEGER CHECK (overall_quality IS NULL OR (overall_quality >= 0 AND overall_quality <= 10)),
  structure_preservation INTEGER CHECK (structure_preservation IS NULL OR (structure_preservation >= 0 AND structure_preservation <= 10)),
  preview_features INTEGER CHECK (preview_features IS NULL OR (preview_features >= 0 AND preview_features <= 10)),
  
  -- Thumbs up/down rating
  thumbs_rating TEXT CHECK (thumbs_rating IS NULL OR thumbs_rating IN ('up', 'down')),
  
  -- Criteria-based evaluation ratings (stored as JSONB)
  criteria_ratings JSONB,
  
  -- Text feedback
  suggestions TEXT,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_feedback_user_id ON feedback(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feedback_translation_id ON feedback(translation_id) WHERE translation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feedback_translation_model ON feedback(translation_model) WHERE translation_model IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_file_type ON feedback(file_type) WHERE file_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feedback_thumbs_rating ON feedback(thumbs_rating) WHERE thumbs_rating IS NOT NULL;

-- Enable Row Level Security (RLS)
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public insert on feedback" ON feedback;
DROP POLICY IF EXISTS "Allow public read on feedback" ON feedback;
DROP POLICY IF EXISTS "Allow public update on feedback" ON feedback;

-- Create policies
CREATE POLICY "Allow public insert on feedback" ON feedback
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow public read on feedback" ON feedback
  FOR SELECT
  USING (true);

CREATE POLICY "Allow public update on feedback" ON feedback
  FOR UPDATE
  USING (true);

-- ============================================================================
-- 5. TRIGGERS AND FUNCTIONS
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop existing triggers if they exist
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
DROP TRIGGER IF EXISTS update_feedback_updated_at ON feedback;

-- Create triggers to auto-update updated_at
CREATE TRIGGER update_users_updated_at 
  BEFORE UPDATE ON users
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_feedback_updated_at 
  BEFORE UPDATE ON feedback
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 6. ANALYTICS VIEWS
-- ============================================================================

-- Drop existing views if they exist
DROP VIEW IF EXISTS feedback_stats;
DROP VIEW IF EXISTS translation_stats;
DROP VIEW IF EXISTS user_activity_summary;

-- View: Feedback Statistics
CREATE VIEW feedback_stats AS
SELECT 
  COUNT(*) as total_feedbacks,
  COUNT(DISTINCT user_id) as unique_users,
  COUNT(DISTINCT translation_id) as unique_translations,
  COUNT(DISTINCT translation_model) as unique_engines,
  COUNT(DISTINCT file_type) as unique_file_types,
  AVG(overall_quality)::NUMERIC(10,2) as avg_overall_quality,
  AVG(structure_preservation)::NUMERIC(10,2) as avg_structure_preservation,
  AVG(preview_features)::NUMERIC(10,2) as avg_preview_features,
  COUNT(CASE WHEN thumbs_rating = 'up' THEN 1 END) as thumbs_up_count,
  COUNT(CASE WHEN thumbs_rating = 'down' THEN 1 END) as thumbs_down_count,
  COUNT(CASE WHEN suggestions IS NOT NULL AND suggestions != '' THEN 1 END) as feedbacks_with_suggestions,
  COUNT(CASE WHEN overall_quality IS NOT NULL THEN 1 END) as quality_ratings_count,
  COUNT(CASE WHEN structure_preservation IS NOT NULL THEN 1 END) as structure_ratings_count,
  COUNT(CASE WHEN preview_features IS NOT NULL THEN 1 END) as preview_ratings_count
FROM feedback;

-- View: Translation Statistics
CREATE VIEW translation_stats AS
SELECT 
  COUNT(*) as total_translations,
  COUNT(DISTINCT user_id) as unique_users,
  COUNT(DISTINCT translation_id) as unique_sessions,
  COUNT(DISTINCT translation_model) as unique_engines,
  COUNT(DISTINCT file_type) as unique_file_types,
  translation_model,
  COUNT(*) as translations_per_engine,
  AVG(LENGTH(source_text))::INTEGER as avg_source_length,
  AVG(LENGTH(translated_text))::INTEGER as avg_translated_length
FROM translation_logs
GROUP BY translation_model;

-- View: User Activity Summary
CREATE VIEW user_activity_summary AS
SELECT 
  u.user_id,
  u.username,
  u.full_name,
  COUNT(DISTINCT tl.translation_id) as translation_sessions,
  COUNT(DISTINCT tl.id) as total_translations,
  COUNT(DISTINCT c.id) as total_comments,
  COUNT(DISTINCT f.id) as total_feedbacks,
  MAX(tl.created_at) as last_translation_at,
  MAX(c.created_at) as last_comment_at,
  MAX(f.created_at) as last_feedback_at
FROM users u
LEFT JOIN translation_logs tl ON u.user_id = tl.user_id
LEFT JOIN comments c ON u.user_id = c.user_id
LEFT JOIN feedback f ON u.user_id = f.user_id
WHERE u.is_active = true
GROUP BY u.user_id, u.username, u.full_name;

-- ============================================================================
-- 7. HELPER QUERIES (For Reference)
-- ============================================================================

-- Query to get all feedback for a specific translation
-- SELECT * FROM feedback WHERE translation_id = 'your-translation-id' ORDER BY created_at DESC;

-- Query to get all comments for a translation
-- SELECT * FROM comments WHERE translation_id = 'your-translation-id' ORDER BY created_at DESC;

-- Query to get all translations by a user
-- SELECT * FROM translation_logs WHERE user_id = 'user_001' ORDER BY created_at DESC;

-- Query to get thumbs up/down counts per engine
-- SELECT translation_model, 
--        COUNT(CASE WHEN thumbs_rating = 'up' THEN 1 END) as thumbs_up,
--        COUNT(CASE WHEN thumbs_rating = 'down' THEN 1 END) as thumbs_down
-- FROM feedback 
-- WHERE thumbs_rating IS NOT NULL
-- GROUP BY translation_model;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
-- After running this script, verify tables were created:
-- SELECT table_name FROM information_schema.tables 
-- WHERE table_schema = 'public' 
-- AND table_name IN ('users', 'translation_logs', 'comments', 'feedback')
-- ORDER BY table_name;
-- ============================================================================




